# 1. Vectors

In [76]:
# Importing important modules which will be used further

import numpy as np
from sympy import *

### 1.1 Creating a Vector

In [144]:
# Creating a vector

vector = np.array([1, 2, 3, 4, 5, 6])
vector

array([1, 2, 3, 4, 5, 6])

### 1.2 Magnitude of a Vector

In [196]:
# Magnitude of vector

v = np.array([7, 3, 8, 2])
magnitude_v = np.linalg.norm(v)               # square root of squared sum of each element

print("Magnitude of vector =", magnitude_v)

Magnitude of vector = 11.224972160321824


### 1.3 Unit Vector

In [197]:
# Finding unit vector

v = np.array([3, 4])
unit_vector = v / (v**2).sum()**0.5           # unit vector = vector / magnitude of vector
print("Unit vector =", unit_vector)

Unit vector = [0.6 0.8]


In [198]:
# Finding unit vector

v = np.array([6, 8, 10])
unit_vector = v / np.linalg.norm(v)
print("Unit vector =", unit_vector)

Unit vector = [0.42426407 0.56568542 0.70710678]


### 1.4 Addition of Two Vectors 

In [199]:
# Addition of two vectors

x = np.array([34,54,76,5,7,48])
y = np.array([31,6,83,53,15,10])

print("Addition of vectors =", x + y)

Addition of vectors = [ 65  60 159  58  22  58]


### 1.5 Subtraction of Two Vectors

In [200]:
# Subtraction of two vectors

x = np.array([34,54,76,5,7,48])
y = np.array([31,6,83,53,15,10])

print("Difference of vectors =", x - y)

Difference of vectors = [  3  48  -7 -48  -8  38]


### 1.6 Product of Scalar to a Vector

In [201]:
# Product of scalar quantity to vector

x = np.array([34,54,76,5,7,48])
print("Product =", 5 * x)

Product = [170 270 380  25  35 240]


### 1.7 Dot Product of Two Vectors

In [202]:
# Dot product of two vectors

x = np.array([2,5,7,8])
y = np.array([6,5,1,10])

print("Dot product =", np.dot(x, y))           # Dot product is scalar

Dot product = 124


### 1.8 Cross Product of Two Vectors

In [203]:
# Cross product of two vectors

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Cross product =", np.cross(a, b))

Cross product = [-3  6 -3]


### 1.9 Projection of One Vector on Other

In [109]:
# Projection of one vector on another

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a_dot_b = np.dot(a, b)
magnitude_b = np.linalg.norm(b)
unit_b = b / np.linalg.norm(b)

a_projection_b = (a_dot_b / magnitude_b) * unit_b

print("Projection of vector a on b =", a_projection_b)

Projection of vector a on b = [1.66233766 2.07792208 2.49350649]


In [236]:
# Projection of one vector on another

a = np.array([0, 2])
b = np.array([4, 0])

a_dot_b = np.dot(a, b)
magnitude_b = np.linalg.norm(b)
unit_b = b / np.linalg.norm(b)

a_projection_b = (a_dot_b / magnitude_b) * unit_b

print("Projection of vector a on b =", a_projection_b)

Projection of vector a on b = [0. 0.]


### 1.10 Change of Basis in Vector Space

In [204]:
# Change of basis

old_vector = [8, 6]
old_basis = np.array([[4, 0],
                      [0, 4]])
new_basis = np.array([[2, 0],
                      [0, 2]])

new_vector = np.linalg.inv(new_basis).dot(old_basis).dot(old_vector)    # new_vector = inv(new_basis).old_basis.old_vector

print("Vector in new basis =", new_vector)

Vector in new basis = [16. 12.]


In [205]:
# Change of basis

old_vector = [8, 6, 3]
old_basis = np.array([[1, 0, 0],
                      [0, 1, 0],
                      [0, 0, 1]])
new_basis = np.array([[2, -8, 3],
                      [0, 2, -5],
                      [1, 3, -4]])

new_vector = np.linalg.inv(new_basis).dot(old_basis).dot(old_vector)    # new_vector = inv(new_basis).old_basis.old_vector

print("Vector in new basis =", new_vector)

Vector in new basis = [ 0.41666667 -1.58333333 -1.83333333]


### 1.11 Span of Vector Space

In [ ]:
# Span of Vector Space

A = Matrix([1, -2, 0])
B = Matrix([-4, 5, 3])

print(A.rref())
print(B.rref())

if A.rref() == B.rref():                                    # For vectors to be in span, RREF should be equal
    print("Both vectors are in span of vector space")
else:
    print("Not in span of vector space")

# 2. Matrix

### 2.1 Creating a Matrix

In [206]:
# Creating a matrix of order 3 x 3 using list

matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

print("Matrix =", matrix)

Matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [233]:
from sympy import *

A = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix =")
A

Matrix =


Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

### 2.2 Accessing Elements of Matrix

In [85]:
# Accessing elements of matrix

matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

print(matrix[1])                   # it will print second row
print(matrix[1][2])                # it will print element of second row and third column
print(matrix[0][-1])               # it will print last element of first row

[4, 5, 6]
6
3


### 2.3 Addition of Matrices

In [210]:
# Addition of matrices (Dimensions of the matrices should be same)

a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

b = [[3, 5, 8],
     [5, 6, 2],
     [9, 4, 1]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(a)):
    for j in range(len(b)):
        result[i][j] = a[i][j] + b[i][j]                 # elementwise addition

print("Addition =")

for r in result:
    print(r)

Addition =
[4, 7, 11]
[9, 11, 8]
[16, 12, 10]


In [211]:
# Addition of matrices (Dimensions of the matrices should be same)

A = np.array(([3,1],[6,4]))
B = np.array(([1,8],[4,2]))
C = np.array(([1,2],[3,4]))

R = A + B + C

print("Addition =")
print(R)

Addition =
[[ 5 11]
 [13 10]]


#### 2.3.1 Associative Property

In [171]:
# A+B = B+A

A = np.array(([3,1],[6,4]))
B = np.array(([1,8],[4,2]))

R1 = A + B
R2 = B + A

print("A + B =\n", R1)
print("B + A =\n", R2)
print("Hence A+B = B+A")

A + B =
 [[ 4  9]
 [10  6]]
B + A =
 [[ 4  9]
 [10  6]]
Hence A+B = B+A


### 2.4 Subtraction of Matrices

In [212]:
# Subtraction of matrices (Dimensions of the matrices should be same)

a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

b = [[3, 5, 8],
     [5, 6, 2],
     [9, 4, 1]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(a)):
    for j in range(len(b)):
        result[i][j] = a[i][j] - b[i][j]           # elementwise difference

print("Difference =")

for r in result:
    print(r)

Difference =
[-2, -3, -5]
[-1, -1, 4]
[-2, 4, 8]


In [213]:
# Subtraction of matrices (Dimensions of the matrices should be same)

A = np.array(([3,1],[6,4]))
B = np.array(([1,8],[4,2]))

R = A - B

print("Difference =")
print(R)

Difference =
[[ 2 -7]
 [ 2  2]]


### 2.5 Multiplication of Matrices

In [214]:
# Multiplication of matrices (number of columns of one matrix should be equal to number of rows of other matrix)

a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

b = [[3, 5, 8],
     [5, 6, 2],
     [9, 4, 1]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(a)):
 
    # iterating by column by B
    for j in range(len(b[0])):
 
        # iterating by rows of B
        for k in range(len(b)):
            result[i][j] += a[i][k] * b[k][j]

print("Product =")

for r in result:
    print(r)

Product =
[40, 29, 15]
[91, 74, 48]
[142, 119, 81]


In [215]:
# Matrix multiplication

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])  
array2 = np.array([[9,8,7],[6,5,4],[3,2,1]])  

result = np.matmul(array1,array2)  

print("Product =\n", result)

Product =
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


#### 2.5.1 AxB is not equal to BxA

In [150]:
# Multiplication of matrices
# AxB

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])  
array2 = np.array([[9,8,7],[6,5,4],[3,2,1]])  

result12 = np.matmul(array1,array2)
print("A x B =\n", result12)
    
# BxA

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])  
array2 = np.array([[9,8,7],[6,5,4],[3,2,1]])  

result21 = np.matmul(array2,array1)
print("B x A =\n", result21)
    
print("It is evident that AxB is not equal to BxA")

A x B =
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
B x A =
 [[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]
It is evident that AxB is not equal to BxA


### 2.6 Elementwise Multiplication of Matrices

In [216]:
# Elementwise Multiplication

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])  
array2 = np.array([[9,8,7],[6,5,4],[3,2,1]])  

result = np.multiply(array1,array2)  

print("Elementwise Product =\n", result)  

Elementwise Product =
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


### 2.7 Transpose of Matrix

In [235]:
# Transpose of matrix (interchanges rows and columns)

X = [[1, 2],
     [3, 4],
     [5, 6]]

result = [[0,0,0],
         [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        result[j][i] = X[i][j]

print("Transpose of matrix =")

for r in result:
    print(r)

Transpose of matrix =
[1, 3, 5]
[2, 4, 6]


In [218]:
# Transpose of Matrix

X = [[1, 2],
     [3, 4],
     [5, 6]]

print("Transpose of matrix =")

print(np.transpose(X))

Transpose of matrix =
[[1 3 5]
 [2 4 6]]


### 2.8 Inverse of Matrix

In [222]:
# Inverse of matrix

a = [[1,-1],[1,2]]
x = np.array(a)
inverse = np.linalg.inv(x)                  # if determinant of matrix is non-zero, matrix is invertible

print("Inverse of matrix =\n", inverse)

Inverse of matrix =
 [[ 0.66666667  0.33333333]
 [-0.33333333  0.33333333]]


#### 2.8.1 Inverse(Inverse(Matrix)) = Matrix

In [100]:
# inv(inv(A)) = A

x = np.array(a)
inv_inv_x = np.linalg.inv(np.linalg.inv(x))

print("Matrix =\n", x)
print("Inverse of inverse of matrix =\n", inv_inv_x)

Matrix =
 [[ 1 -1]
 [ 1  2]]
Inverse of inverse of matrix =
 [[ 1. -1.]
 [ 1.  2.]]


#### 2.8.2 Inverse of Singular Matrix is not Possible

In [164]:
x = np.array([[1, 4, 5], [2, 8, 10], [8, 4, 1]])
determinant = np.linalg.det(x)

print('Determinant =', determinant)

try:
    inverse = np.linalg.inv(x)
    print(inverse)
except:
    print("Inverse of Singular matrix is not Possible")

Determinant = 0.0
Inverse of Singular matrix is not Possible


### 2.9 Rank of Matrix

In [223]:
# Rank of matrix

x = np.array([[1, 0, 5], [4, 7, 9], [8, 4, 6]])
rank = np.linalg.matrix_rank(x)

print("Rank of matrix =", rank)

Rank of matrix = 3


### 2.10 Determinant of Matrix

In [86]:
# Determinant of matrix

x = np.array([[1, 4, 5], [4, 3, 9], [8, 4, 1]])
determinant = np.linalg.det(x)

print('Determinant =', determinant)

Determinant = 198.99999999999997


#### 2.10.1 Det(A) = Det(Transpose(A))

In [93]:
x = np.array([[1, 4, 5], [4, 3, 9], [8, 4, 1]])

det_x = np.linalg.det(x)
det_trans_x = np.linalg.det(np.transpose(x))

print('Determinant =', det_x)
print('Determinant of transpose =', det_trans_x)
print("Thus, determinant of matrix and its transpose is same")

Determinant = 198.99999999999997
Determinant of transpose = 198.99999999999997
Thus, determinant of matrix and its transpose is same


### 2.11 Singular Matrix

In [167]:
# Singular matrix (ie, determinant of matrix is zero)

x = np.array([[1, 2, 3], [2, 4, 6], [1, 4, 6]])
determinant = np.linalg.det(x)

print('determinant =', determinant)

if determinant == 0:                            # determinant of singular matrix is zero
    print("It is a singular matrix")
else:
    print("It is not a singular matrix")

determinant = 0.0
It is a singular matrix


### 2.12 Cofactor of Matrix

In [225]:
# Cofactor of matrix

from sympy import *

A = Matrix([[1,2,0],[0,3,0],[0,7,1]])
print("Cofactor of matrix =")
A.adjugate().T                               # Transpose of adjoint of matrix

Cofactor of matrix =


Matrix([
[ 3, 0,  0],
[-2, 1, -7],
[ 0, 0,  3]])

### 2.13 Adjoint of Matrix

In [226]:
# Adjoint of matrix

from sympy import *

A = Matrix([[1,2,0],[0,3,0],[0,7,1]])
print("Adjoint of matrix =")
A.adjugate()

Adjoint of matrix =


Matrix([
[3, -2, 0],
[0,  1, 0],
[0, -7, 3]])

### 2.14 RREF of Matrix

In [228]:
# RREF of matrix

from sympy import *

A = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("RREF of matrix =")
print(A.rref())                      # matrix part give RREF, second part gives index of pivot values

RREF of matrix =
(Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))


### 2.15 Identity Matrix

In [229]:
# Identity matrix

I = np.identity(3)
print("Identity matrix =\n", I)

Identity matrix =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 3. Solutions of Linear Equations

In [231]:
# Solving linear equations
# Let's say we have three linear equations
# 1. 4x - 7y + 3z = 12
# 2. 6x + 8y - 2z = 32
# 3. 7x - 3y - 4z = 4

# We can represent it in the form of matrices

A = np.array([[4, -7, 3],
              [6, 8, -2],
              [7, -3, -4]])

B = np.array([12, 32, 4])

inverse_A = np.linalg.inv(A)

X = np.dot(inverse_A, B)

print("Solution of equations =", X)

Solution of equations = [3.78378378 2.16216216 4.        ]


### 3.1 Consistent and Unique Solutions

In [232]:
# Solving linear equations
# Let's say we have three linear equations
# 1. 4x - 7y + 3z = 12
# 2. 6x + 8y - 2z = 32
# 3. 7x - 3y - 4z = 4

# We can represent it in the form of matrices

A = np.array([[4, -7, 3],
              [6, 8, -2],
              [7, -3, -4]])

B = np.array([12, 32, 4])

X = np.linalg.solve(A, B)

print("Solution of equations =", X)

Solution of equations = [3.78378378 2.16216216 4.        ]


### 3.2 Inconsistent and No Solution

In [165]:
# These set of linear equations are inconsistent

A = np.array([[4, 2],
              [8, 4]])

B = np.array([12, 28])

try:
    X = np.linalg.solve(A, B)
    print(X)
except:
    print("Inconsistent system of equations")


Inconsistent system of equations


### 3.3 Consistent and Infinite Solutions

In [166]:
# These set of linear equations are consistent with infinite solutions

A = np.array([[4, 2],
              [8, 4]])

B = np.array([12, 24])

try:
    X = np.linalg.solve(A, B)
    print(X)
except:
    print("Infinite solutions")

Infinite solutions
